# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


# 1. get blogs index
GET http://reduxblog.herokuapp.com/api/posts?key=skfldbwkqkq12#$
Accept: application/json

###

# 2. get blog detail
GET http://reduxblog.herokuapp.com/api/posts/315392?key=skfldbwkqkq12#$
Accept: application/json

###


# 3. Create new Post
POST http://reduxblog.herokuapp.com/api/posts
Content-Type: application/json

{
  "key": "skfldbwkqkq12#$",
  "id": 100,
  "title": "hi",
  "categories": "greetings",
  "content": "hi, hello, good moring"
}

###


# Delete Post
DELETE http://reduxblog.herokuapp.com/api/posts/315390
Content-Type: application/json

{
  "key": "skfldbwkqkq12#$",
  "id": 100,
  "title": "hi",
  "categories": "greetings",
  "content": "hi, hello, good moring"
}
###
